FROM node:22-alpine

WORKDIR /app

COPY ./vite/package.json ./package.json

RUN npm i

COPY ./vite /app

COPY ./docker/entrypoint_vite.sh /app/

RUN apk add --no-cache dos2unix && dos2unix /app/entrypoint_vite.sh

RUN chmod +x /app/entrypoint_vite.sh

EXPOSE 8305

CMD [ "sh", "/app/entrypoint_vite.sh" ]
