FROM python:3.12-bullseye

WORKDIR /app

COPY ./fastapi/requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

COPY ./fastapi /app

EXPOSE 8302

CMD ["fastapi", "run", "main.py", "--port", "8302"]
